services:

  web:
    image: nginx:latest
    container_name: app_web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: app_db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always # O container sempre tentará reiniciar em caso de falha

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
