apiVersion: v1
kind: Service
metadata:
  name: {{ include "app5-chart.fullname" . }}
  labels:
    {{- include "app5-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "app5-chart.selectorLabels" . | nindent 4 }}
