apiVersion: v1
kind: Service
metadata:
  name: {{ include "meu-app-demo.fullname" . }}
  labels:
    {{- include "meu-app-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "meu-app-demo.selectorLabels" . | nindent 4 }}
