{{- /* Service para o Frontend */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app5-v2-chart.fullname" . }}-frontend
  labels:
    {{- include "app5-v2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app5-v2-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

---

{{- /* Service para o Processor (exemplo de service interno) */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app5-v2-chart.fullname" . }}-processor
  labels:
    {{- include "app5-v2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
spec:
  type: ClusterIP
  ports:
    # O processor não tem porta, mas um service pode existir mesmo assim
    # para futuras implementações ou para seleção de pods.
    - port: 8080
      targetPort: 8080 # Placeholder
  selector:
    {{- include "app5-v2-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: processor

{{- /* Adicione outros services internos para aggregator, metric-generator, etc., se necessário */ -}}