# java-app-secrets/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-app-secrets.fullname" . }}-secret
  labels:
    {{- include "java-app-secrets.labels" . | nindent 4 }}
type: Opaque
data:
  # O Helm não codifica automaticamente, então use 'b64enc' para garantir a codificação.
  SECRET_API_KEY: {{ .Values.secret.api_key | b64enc | quote }}
  SECRET_DB_USER: {{ .Values.secret.db_user | b64enc | quote }}
  SECRET_DB_PASS: {{ .Values.secret.db_pass | b64enc | quote }}
