# values.yaml para app2 (multi-container)

replicaCount: 1

# Configurações do container de Frontend
frontend:
  image:
    repository: quay.io/hygorhernane/app2-front
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    port: 8080
    type: ClusterIP
  # Sondas para o frontend
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080

# Configurações do container de Backend
backend:
  image:
    repository: quay.io/hygorhernane/app2-back
    pullPolicy: IfNotPresent
    tag: "latest"
  port: 8081
  # Sondas para o backend
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
  readinessProbe:
    httpGet:
      path: /ready
      port: 8081
  # Variáveis de ambiente para o backend se conectar ao DB
  # Estes valores devem ser gerenciados por um Secret em produção
  env:
    DB_HOST: "postgres-service"
    DB_PORT: "5432"
    POSTGRES_DB: "mydb"
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "mypassword"

# As demais configurações (ingress, resources, etc.) podem ser mantidas
# e aplicadas a ambos os contêineres se necessário, ou customizadas.
